---
- src: https://github.com/AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"
  name: clickhouse

- src: ./roles/vector-role
  name: vector-role

- src: ./roles/lighthouse-role
  name: lighthouse-role
