---
vector_version: "0.34.1"
vector_architecture: "x86_64"
vector_package: "vector-{{ vector_version }}-{{ vector_architecture }}-unknown-linux-gnu.tar.gz"
vector_url: "https://packages.timber.io/vector/{{ vector_version }}/{{ vector_package }}"
vector_install_dir: "/opt/vector"
vector_config_dir: "/etc/vector"
