---
galaxy_info:
  role_name: vector
  namespace: dun9dev
  author: dun9dev
  description: Role for installing and configuring Vector
  company: none
  license: MIT
  min_ansible_version: 2.10
  platforms:
    - name: Ubuntu
      versions:
        - 20.04
        - 22.04
        - 24.04
    - name: EL
      versions:
        - 8
  galaxy_tags:
    - vector
    - observability
    - logging
dependencies: []
